/* Generated By:JavaCC: Do not edit this line. SimplePCRETreeConstants.java Version 5.0 */
package parser;

public interface SimplePCRETreeConstants
{
  public int JJTRE = 0;
  public int JJTUNION = 1;
  public int JJTVOID = 2;
  public int JJTSEQUENCE = 3;
  public int JJTSTAR = 4;
  public int JJTPLUS = 5;
  public int JJTOPTIONAL = 6;
  public int JJTCOUNT = 7;
  public int JJTANY = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTRANGE = 10;


  public String[] jjtNodeName = {
    "Re",
    "union",
    "void",
    "Sequence",
    "Star",
    "Plus",
    "Optional",
    "Count",
    "Any",
    "Identifier",
    "Range",
  };
}
/* JavaCC - OriginalChecksum=8416e39b8458934223922e52ede64651 (do not edit this line) */
